/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import lombok.extern.slf4j.Slf4j;

import java.util.logging.Logger;

@Slf4j
public class Library {
    public boolean someLibraryMethod() {
        log.info("11111");
        return true;
    }
}
